# -*- coding: utf-8 -*-
"""python.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11O5fetgR27fmY7_5i9xP8CQkz5pwTLn5
"""

x=10

y=20

x+y

x-y

x*y

x/y

x=10
type(x)

x=10.5
type(x)

x="The World is yours"

print(x)

type(x)

x="Jeswin"
y="Thomas"
x+y

type (x)

x=10
y=20
x+y

type(x)

x="10"
y="20"
x+y

type(x)

x=input()

print(x)
type(x)

y=int(x)
y

type(y)

x=int(input())

type(x)

x=int(input("enter a number"))

print(x)

x=int(input("enter a number 1 :"))
y=int(input("Enter a number 2 :"))

x+y

x-y

x*y

x/y

x**y

x//y

P=int(input("Enter initial balance ="))
R=int(input("Enter annual interst rate ="))
t=int(input("time in years ="))
r=R/100
A=P*(1+r*t)
print("Final Amount :",A)

x*2

import math

math.pow(2,2)

2**2

P=int(input("Enter initial balance ="))
R=int(input("Enter annual interst rate ="))
t=int(input("time in years ="))
N=int(input("Enter interset compunded ="))
r=R/100
n=12/N
A=P*(1+r/n)*n*t
print("Amount at the end :",A)

